### ISSUE TITLE
Is it supporting Xcode 13.3?

### ISSUE THREAD

**Issue by harryworld** [iKenndac/xcode-streamdeck-plugin#9]
Thanks for making this, and this is such a great replacement of TouchBar

However, it seems become malfunction after upgrading to Xcode 13.3. Is there a setting or something to control this?

**Comment by iKenndac** [comment]
All of the actions still work for me with Xcode 13.3.1.

**Comment by harryworld** [comment]
Thanks, I confirmed that it's working in Xcode 13.3.1
